# docker-compose.replay.yml
#
# Overrides for replay mode.
# This file specifies the command to run the bot in replay mode and
# ensures the correct configuration file is used.

services:
  bot:
    # The main docker-compose.yml already mounts the entire ./config directory.
    # We just need to override the command to point to the correct file and add the -replay flag.
    command: ./obi-scalp-bot -replay -config /app/config/config-replay.yaml
    healthcheck:
      disable: true
    restart: "no"
