services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
      - ./data/params:/data/params
    working_dir: /app
    environment:
      - DB_HOST=timescaledb
      - STORAGE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@timescaledb:5432/${DB_NAME}
    networks:
      - bot_network
    depends_on:
      - timescaledb

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obi-scalp-bot
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./data/params:/data/params
      - ./config:/app/config:ro
    entrypoint: ["/app/entrypoint.sh"]
    # The trade_config.yaml is now loaded from /data/params by default in the Go app
    command: ["-config", "/app/config/app_config.yaml"]
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    ports:
      - "8080:8080" # Expose healthcheck port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      timescaledb:
        condition: service_healthy
      optimizer:
        condition: service_healthy
    networks:
      - bot_network

  bot-simulate:
    build:
      context: .
      dockerfile: Dockerfile
    # image: obi-scalp-bot-image:latest
    container_name: obi-scalp-bot-simulate
    entrypoint: ["/usr/local/bin/obi-scalp-bot"]
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bot_network

  timescaledb:
    image: timescale/timescaledb-ha:pg14.9-ts2.11.2
    container_name: timescaledb-obi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d/01_schema

    command: postgres -c timezone=Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - bot_network

  report-generator:
    build:
      context: .
      dockerfile: cmd/report/Dockerfile
    container_name: obi-scalp-report-generator
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@timescaledb:${DB_PORT}/${DB_NAME}?sslmode=disable
      - REPORT_INTERVAL_MINUTES=1
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bot_network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-obi
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - bot_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - bot_network
    depends_on:
      - timescaledb

  optimizer:
    build:
      context: .
      dockerfile: optimizer/Dockerfile
    container_name: obi-scalp-optimizer
    working_dir: /app
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./data/params:/data/params
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
      - STORAGE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@timescaledb:5432/${DB_NAME}
    networks:
      - bot_network
    depends_on:
      timescaledb:
        condition: service_healthy
    command: python -m optimizer.main
    healthcheck:
      test: ["CMD-SHELL", "test -f /data/params/optimizer_config.yaml"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 5s
    restart: always

  drift-monitor:
    build:
      context: .
      dockerfile: optimizer/Dockerfile
    container_name: obi-scalp-drift-monitor
    working_dir: /app
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./data/params:/data/params
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    networks:
      - bot_network
    depends_on:
      timescaledb:
        condition: service_healthy
    command: python -m optimizer.drift_monitor

  wfo-runner:
    build:
      context: .
      dockerfile: optimizer/Dockerfile.wfo
    container_name: obi-scalp-wfo-runner
    working_dir: /app
    volumes:
      - .:/app
      - ./data/params:/data/params
      - ./data/wfo_results:/app/data/wfo_results
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
      - PYTHONPATH=/app
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  timescaledb_data:
  grafana_data:
  params_volume:
