services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    networks:
      - bot_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obi-scalp-bot
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
    entrypoint: ["/usr/local/bin/obi-scalp-bot"]
    command: ["-config", "/app/config/config.yaml"]
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    ports:
      - "8080:8080" # Expose healthcheck port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - bot_network

  bot-replay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obi-scalp-bot-replay
    entrypoint: ["/usr/local/bin/obi-scalp-bot"]
    volumes:
      - ./.env:/app/.env:ro
      - ./config:/app/config:ro
      - ./pkg:/app/pkg:ro
    command: ["-replay", "-config", "/app/config/config-replay.yaml"]
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - bot_network

  bot-simulate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obi-scalp-bot-simulate
    entrypoint: ["/usr/local/bin/obi-scalp-bot"]
    volumes:
      - ./config:/app/config:ro
      - ./pkg:/app/pkg:ro
      - ./simulation:/app/simulation:ro
    networks:
      - bot_network

  db-init:
    image: postgres:14
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST: timescaledb
      POSTGRES_USER: ${DB_USER:-your_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_db_password}
      POSTGRES_DB: ${DB_NAME:-obi_scalp_bot_db}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        /docker-entrypoint-initdb.d/init-db.sh
    networks:
      - bot_network
    depends_on:
      timescaledb:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb-ha:pg14.9-ts2.11.2
    container_name: timescaledb-obi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-your_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_db_password}
      POSTGRES_DB: ${DB_NAME:-obi_scalp_bot_db}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - bot_network

  report-generator:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: report-generator
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    networks:
      - bot_network
    depends_on:
      - timescaledb
    command: ["sleep", "infinity"]

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-obi
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  timescaledb_data:
  grafana_data:


      