version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obi-scalp-bot
    volumes:
      # Mount the local .env file into the container.
      # Create a .env file from .env.sample and fill in your API keys.
      - ./.env:/app/.env:ro
      # Mount the local config file into the container for easier development.
      # Changes to config.yaml on the host will be reflected in the container without rebuilding.
      - ./config/config.yaml:/app/config/config.yaml:ro
    env_file:
      - .env # Loads environment variables from the .env file at the root of the project
    restart: unless-stopped
    # ports:
      # - "8080:8080" # Example: expose port 8080 for health checks if implemented
    # command: ["./obi-scalp-bot", "-config", "config/config.yaml"] # Optional: override CMD in Dockerfile
    # The Dockerfile already sets up the entrypoint and default config path.
    # This command is only needed if you want to override it.

# Future services like TimescaleDB and Grafana will be added here.
# volumes:
#   timescaledb_data:
# networks:
#   bot_network:
