FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install Docker client
RUN apt-get update && apt-get install -y docker.io

COPY . .

CMD ["python", "optimizer.py"]
