# /grafana/provisioning/datasources/datasource.yml

apiVersion: 1

datasources:
  - name: 'TimescaleDB (Production)'
    type: postgres
    url: timescaledb:5432
    user: '${DB_USER}'
    database: '${DB_NAME}'
    secureJsonData:
      password: '${DB_PASSWORD}'
    jsonData:
      sslmode: 'disable' # For internal network, 'require' is better for prod.
      postgresVersion: 14
      timescaledb: true
    uid: obi_scalp_bot_db
    readOnly: true
