# OBI-Scalp-Bot アプリケーション設定ファイル (app_config.yaml)
#
# このファイルは、ボットのコア機能、データベース接続、パフォーマンスなど、
# システム全体の基本的な挙動を制御します。

# ------------------------------------------------------------------------------
# アプリケーション全体設定 (Global Application Settings)
# ------------------------------------------------------------------------------

# log_level: 出力するログの詳細レベル。"debug", "info", "warn", "error"から選択。
# 通常は "info" を使用し、問題調査時には "debug" に変更します。
# 環境変数 'LOG_LEVEL' で上書き可能です。
log_level: "debug"

# obi_calculator_channel_size: OBI計算結果を格納するチャネルのバッファサイズ。
# インジケーター計算（プロデューサー）とシグナル評価（コンシューマー）の間の
# 速度差を吸収します。"output channel is full" 警告が頻発する場合、
# この値を増やすことでデータドロップを減らせますが、メモリ使用量が増加します。
obi_calculator_channel_size: 300

# signal_evaluation_interval_ms: シグナル評価ロジックを実行する間隔（ミリ秒）。
# OBIの計算は高頻度で行われますが、シグナルの最終評価はこの間隔で実行されます。
# この値を大きくするとCPU負荷は下がりますが、市場の急な変動への反応が遅れる可能性があります。
# 逆に小さくしすぎると、OBIチャネルの警告が再発する可能性があります。
# デフォルト値: 500
signal_evaluation_interval_ms: 500

# ------------------------------------------------------------------------------
# 注文執行エンジン設定 (Order Execution Engine)
# ------------------------------------------------------------------------------
order:
  # timeout_seconds: 指値注文が約定しない場合に自動キャンセルされるまでの時間（秒）。
  # 市場の流動性に応じて調整してください。
  timeout_seconds: 15

  # poll_interval_ms: 注文の約定状況を取引所に確認しにいく頻度（ミリ秒）。
  # 取引所のAPIレート制限を考慮して設定してください。
  poll_interval_ms: 2000

# ------------------------------------------------------------------------------
# データベース設定 (Database)
# ------------------------------------------------------------------------------
# 環境変数 (DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, DB_SSLMODE) で上書き可能です。
database:
  # host: データベースサーバーのホスト名またはIPアドレス。
  host: "timescaledb"
  # port: データベースサーバーのポート番号。
  port: 5432
  # user: データベース接続ユーザー名。
  user: "bot"
  # password: データベース接続パスワード。
  password: "password"
  # name: 接続するデータベース名。
  name: "coincheck_data"
  # sslmode: SSLモード。"disable", "require", "verify-full" など。
  sslmode: "disable"

# ------------------------------------------------------------------------------
# データベース書き込み設定 (Database Writer)
# ------------------------------------------------------------------------------
db_writer:
  # batch_size: 一度にDBへ書き込む最大レコード数。
  # 大きくすると書き込み効率は向上しますが、メモリ使用量も増加します。
  batch_size: 100
  # write_interval_seconds: バッファからDBへの書き込みを行う間隔（秒）。
  write_interval_seconds: 5
  # enable_async: DBへの書き込みを非同期で行うか。
  # `false` の場合、書き込み処理が完了するまで次の処理がブロックされます。
  enable_async: false

# ------------------------------------------------------------------------------
# PnLレポート設定 (PnL (Profit and Loss) Report)
# ------------------------------------------------------------------------------
pnl_report:
  # interval_minutes: PnL（損益）レポートを生成する間隔（分）。
  interval_minutes: 1
  # max_age_hours: 生成したPnLレポートをDBに保存する最大期間（時間）。
  # この期間を過ぎた古いデータは自動的に削除されます。
  max_age_hours: 24

# ------------------------------------------------------------------------------
# アラート設定 (Alerting)
# ------------------------------------------------------------------------------
# 現在、アラート機能は実装されていません。
# 将来的に、エラーや重要なイベントを通知する機能を追加する可能性があります。
alert:
  enabled: false
