# OBI-Scalp-Bot アプリケーション設定ファイル (app_config.yaml)

# --- アプリケーション設定 ---
# ボットの動作、データベース接続、リプレイモードなど、システム全体に関わる設定です。

# ログレベル ("debug", "info", "warn", "error")
log_level: "info"

# 注文執行エンジン設定
order:
  # 注文タイムアウト時間（秒）
  # 指値注文がこの時間内に約定しない場合、自動的にキャンセルされます。
  # 値を大きくすると約定の機会は増えますが、相場変動リスクも高まります。
  # 値を小さくすると機会損失は減りますが、約定チャンスを逃す可能性もあります。
  timeout_seconds: 15
  # 注文状況確認のポーリング間隔（ミリ秒）
  # 注文の約定状況を取引所に確認しにいく頻度です。
  # 売買戦略には直接影響しませんが、APIリクエスト頻度に関わるため、短くしすぎないでください。
  poll_interval_ms: 2000

# データベース接続設定
database:
  host: "timescaledb"
  port: 5432
  user: ""
  password: ""
  name: "obi_scalp_bot_db"
  sslmode: "disable"

# データベース書き込み設定
db_writer:
  # 一度に書き込むバッチサイズ
  batch_size: 100
  # 書き込み間隔（秒）
  write_interval_seconds: 5
  # 非同期書き込みの有効化
  enable_async: false

# PnLレポート設定
pnl_report:
  # レポート生成間隔（分）
  interval_minutes: 1
  # レポートの最大保存期間（時間）
  max_age_hours: 24

# --- アラート設定 ---
alert:
  discord:
    # Discord通知を有効にするか (デフォルト: false)
    enabled: false
    # Discord Botのトークン (環境変数 DISCORD_BOT_TOKEN で上書きされます)
    bot_token: "dummy_token"
    # 通知を送信するユーザーのID (環境変数 DISCORD_USER_ID で上書きされます)
    user_id: "dummy_user_id"
