adaptive_position_sizing:
  enabled: true
  min_ratio: 0.5
  num_trades: 5
  reduction_step: 0.9
long:
  obi_threshold: 0.6098637368217219
  sl: -296
  tp: 149
lot_max_ratio: 0.045
order_ratio: 0.15
pair: btc_jpy
risk:
  max_drawdown_percent: 8
  max_position_jpy: 500000.0
short:
  obi_threshold: -1.0205448472873493
  sl: -255
  tp: 90
signal:
  hold_duration_ms: 695
  slope_filter:
    enabled: true
    period: 12
    threshold: 0.15915343142704597
spread_limit: 69
twap:
  enabled: false
  exit_ratio: 0.5
  interval_seconds: 5
  max_order_size_btc: 0.01
  partial_exit_enabled: false
  profit_threshold: 0.5
volatility:
  dynamic_obi:
    enabled: true
    max_threshold_factor: 1.0267270609364305
    min_threshold_factor: 0.7178710836461488
    volatility_factor: 1.4659684705429334
  ewma_lambda: 0.15
