# OBI-Scalp-Bot 設定ファイル (config.yaml)
log_level: "info"
pair: "btc_jpy"
spread_limit: 60
lot_max_ratio: 0.05
order_ratio: 0.2

long:
  obi_threshold: 0.40
  tp: 25
  sl: -10

short:
  obi_threshold: -0.27
  tp: 25
  sl: -12

volatility:
  ewma_lambda: 0.3
  dynamic_obi:
    enabled: true
    volatility_factor: 1.3
    min_threshold_factor: 0.7
    max_threshold_factor: 1.8

database:
  host: "timescaledb"
  port: 5432
  user: ""
  password: ""
  name: "obi_scalp_bot_db"
  sslmode: "disable"

db_writer:
  batch_size: 100
  write_interval_seconds: 5
  enable_async: false

replay:
  start_time: "2025-07-13T00:00:00Z"
  end_time: "2025-07-14T00:00:00Z"

twap:
  enabled: false
  max_order_size_btc: 0.01
  interval_seconds: 10
