# OBI-Scalp-Bot 設定ファイル (config.yaml)
log_level: "info"
pair: "btc_jpy"
spread_limit: 40
lot_max_ratio: 0.05
order_ratio: 0.5

long:
  obi_threshold: 0.25
  tp: 15
  sl: -10

short:
  obi_threshold: -0.27
  tp: 18
  sl: -12

volatility:
  ewma_lambda: 0.1
  dynamic_obi:
    enabled: true
    volatility_factor: 1.0
    min_threshold_factor: 0.5
    max_threshold_factor: 2.0

database:
  host: "timescaledb"
  port: 5432
  user: ""
  password: ""
  name: "obi_scalp_bot_db"
  sslmode: "disable"

db_writer:
  batch_size: 100
  write_interval_seconds: 5
  enable_async: false

replay:
  start_time: "2025-07-13T00:00:00Z"
  end_time: "2025-07-14T00:00:00Z"

twap:
  enabled: false
  max_order_size_btc: 0.01
  interval_seconds: 10
