pair: btc_jpy
spread_limit: 40
lot_max_ratio: 0.05
long:
  obi_threshold: 0.25
  tp: 15
  sl: -10
short:
  obi_threshold: 0.27
  tp: 18
  sl: -12
volatility:
  ewma_lambda: 0.1

# Database Configuration
# These settings are for the TimescaleDB connection.
# Sensitive information like passwords should ideally be set via environment variables.
database:
  host: "localhost" # Or the Docker service name, e.g., "timescaledb"
  port: 5432
  user: "your_db_user"       # Replace with your TimescaleDB username
  password: "your_db_password" # Replace with your TimescaleDB password (or set via DB_PASSWORD env var)
  name: "obi_scalp_bot_db" # Replace with your database name
  sslmode: "disable"      # Common for local dev; use "require" or "verify-full" for prod

# DBWriter Configuration
# Settings for the service that writes data to TimescaleDB.
db_writer:
  batch_size: 100             # Number of records to batch before writing to DB
  write_interval_seconds: 5 # Interval in seconds for periodic writes (if async/batching)
  enable_async: false         # Enable asynchronous writing (not yet fully implemented in writer.go)
