# optimizer/optimizer.py で使用する定数を定義します。
# このファイルが存在しない場合、オプティマイザは起動に失敗します。

# --- 基本設定 ---
# パフォーマンスチェックを実行する間隔（秒単位）。
# 環境変数 'CHECK_INTERVAL_SECONDS' が設定されていればそちらを優先します。
# 例: 300
check_interval_seconds: 900

# パラメータファイルやデータベースが保存されるディレクトリのパス。
# 環境変数 'PARAMS_DIR' が設定されていればそちらを優先します。
# 例: /data/params
params_dir: 'data/params'

# --- 最適化設定 ---
# Optunaが試行する回数。
# 例: 100
n_trials: 800

# ウォームスタートで読み込む過去のTrialの最大数。
# これを超える数のTrialが見つかった場合、最新のものからこの数だけが使われます。
# 例: 250
warm_start_max_trials: 200

# --- 合格/不合格基準 ---

# OOS評価での合格基準となるシャープレシオの最小値。
# これを下回るパラメータは不合格となります。
# 例: 0.5
oos_min_sharpe_ratio: 0.5

# --- リトライ & 早期停止基準 ---
# OOS評価で不合格だった場合に、IS(In-Sample)の上位から何位までのパラメータを試すかの最大数。
# 例: 5
max_retry: 20

# OOS評価のシャープレシオが著しく低い結果が連続した場合に、リトライを早期停止する回数。
# 例: 2
early_stop_count: 20

# 早期停止のトリガーとなるシャープレシオの閾値の割合。
# (OOS_MIN_SHARPE_RATIO * この値) を下回る結果が続くと早期停止します。
# 例: 0.7
early_stop_threshold_ratio: 0.7

# (現在未実装) 将来的に、OOS評価で良い結果が得られなかった場合に再最適化をトリガーするかどうか。
# 例: true
trigger_reoptimize: true

# --- サンプルサイズガード ---
# シミュレーション結果を有効と見なすための最小実行取引回数。
# これに満たない試行は評価されません。
# 例: 5000
min_executed_trades: 5000

# OOS評価での合格基準となる最小取引回数。
# これを下回るパラメータは不合格となります。
# 例: 10
oos_min_trades: 10

# シミュレーション結果を有効と見なすための最小オーダーブックスナップショット数。
# これに満たないデータセットでは警告が出力されます（現在未実装）。
# 例: 100000
min_order_book_snapshots: 100000

# --- 枝刈り設定 ---
# IS最適化中に、ここで設定した取引回数に満たない試行を枝刈り（pruning）します。
# jobファイルで 'min_trades' が指定されている場合はそちらを優先します。
# 例: 30
min_trades_for_pruning: 10

# --- Stability Analysis Settings ---
# Settings for the objective regularization to find robust parameters.
stability_analysis:
  # Number of additional simulation runs with jittered parameters.
  n_runs: 5
  # The factor by which to jitter numerical parameters (e.g., 0.05 for +/- 5%).
  jitter_factor: 0.05
  # The weight of the standard deviation penalty in the final objective score.
  penalty_factor: 0.5

# --- Analyzer Settings ---
analyzer:
  # The quantile of top-performing trials to consider for robustness analysis.
  # For example, 0.1 means the top 10% of trials will be analyzed.
  top_trials_quantile: 0.1

# --- Objective Function Weights ---
# The weights for the components of the custom objective function.
# These values determine the importance of each metric in the final score.
objective_weights:
  sharpe_ratio: 1.0
  profit_factor: 1.0
  max_drawdown: 1.0 # Note: The objective function inverts this, so higher is better.
  sqn: 0.5
  trades: 0.5
