# optimizer/optimizer.py で使用する定数を定義します。
# このファイルが存在しない場合、オプティマイザは起動に失敗します。

# ------------------------------------------------------------------------------
# 基本設定 (Basic Settings)
# ------------------------------------------------------------------------------

# check_interval_seconds: パフォーマンスチェックを実行する間隔（秒単位）。
check_interval_seconds: 900

# params_dir: パラメータファイルやデータベースが保存されるディレクトリのパス。
params_dir: 'data/params'

# ------------------------------------------------------------------------------
# 最適化設定 (Optimization Settings)
# ------------------------------------------------------------------------------

# n_trials: 1回の最適化サイクルでOptunaが試行する回数。
n_trials: 1000

# warm_start_max_trials: 過去の学習結果を何件まで読み込むか。
warm_start_max_trials: 100

# min_trades_for_pruning: In-Sample(IS)最適化中に、ここで設定した取引回数に満たない試行を枝刈り（pruning）します。
min_trades_for_pruning: 5

# coarse_to_fine: Coarse-to-Fine（粗から密へ）探索の設定。
coarse_to_fine:
  enabled: true
  coarse_trials: 300
  fine_trials: 200
  top_trials_quantile_for_kde: 0.2

# ------------------------------------------------------------------------------
# 評価と検証の基準 (Evaluation & Validation Criteria)
# ------------------------------------------------------------------------------

# oos_min_sharpe_ratio: Out-of-Sample(OOS)評価での合格基準となるシャープレシオの最小値。
oos_min_sharpe_ratio: 0.5

# oos_min_trades: OOS評価での合格基準となる最小取引回数。
oos_min_trades: 10

# max_retry: OOS評価で不合格だった場合に、ISの上位から何番目までのパラメータを試すか。
max_retry: 5

# early_stop_count: OOS評価で、著しく低いシャープレシオがこの回数連続した場合にリトライを早期停止します。
early_stop_count: 5

# early_stop_threshold_ratio: 早期停止のトリガーとなるシャープレシオの閾値の割合。
early_stop_threshold_ratio: 0.7

# ------------------------------------------------------------------------------
# 高度な設定 (Advanced Settings)
# ------------------------------------------------------------------------------

# objective_weights: Optunaの目的関数の各指標に対する重み付け。
# これらの値は、最終的な評価スコアを計算する際の各指標の重要度を決定します。
# realization_rateを追加し、約定の実現性を重視します。
objective_weights:
  # シャープレシオ: リスク調整後のリターン
  sharpe_ratio: 1.0
  # プロフィットファクター: 総利益 / 総損失
  profit_factor: 1.0
  # 最大ドローダウン: 資産のピークからの最大下落率 (値が大きいほど良いと評価されるように内部で反転されます)
  max_drawdown: 0.5
  # SQN (System Quality Number): システムの品質を示す指標 (SharpeRatio * sqrt(TotalTrades))
  sqn: 0.5
  # 取引回数
  trades: 0.2
  # 約定実現率: シグナル確定数に対する実際の取引数の割合。オーバーフィットの抑制に重要。
  realization_rate: 2.0

# stability_analysis: パラメータの安定性分析（ロバスト性チェック）の設定。
stability_analysis:
  n_runs: 5
  jitter_factor: 0.05
  penalty_factor: 0.75

# analyzer: 最適化結果の分析設定。
analyzer:
  top_trials_quantile: 0.1

# drift_monitor_windows: ドリフトモニターによって最適化がトリガーされた際の、ウィンドウサイズ設定。
drift_monitor_windows:
  major:
    window_is_hours: 4
    window_oos_hours: 1
  normal:
    window_is_hours: 4
    window_oos_hours: 1
  minor:
    window_is_hours: 2
    window_oos_hours: 0.5

# -----------------------------------------------------------------------------
# Walk-Forward Optimization (WFO) Runner Settings
# -----------------------------------------------------------------------------
wfo_runner:
  start_date: "2024-04-01T00:00:00Z"
  end_date: "2024-07-01T00:00:00Z"
  is_window_days: 45
  oos_window_days: 15
  step_days: 15
