pair: "btc_jpy"
order_amount: 0.01
spread_limit: 0.005
lot_max_ratio: 1.0
order_ratio: 1.0

long:
  obi_threshold: 0.5
  tp: 10000.0
  sl: -5000.0

short:
  obi_threshold: -0.5
  tp: 10000.0
  sl: -5000.0

volatility:
  ewma_lambda: 0.94
  dynamic_obi:
    enabled: true
    volatility_factor: 0.1
    min_threshold_factor: 0.8
    max_threshold_factor: 1.2

twap:
  enabled: false
  max_order_size_btc: 0.1
  interval_seconds: 60
  partial_exit_enabled: false
  profit_threshold: 10000.0
  exit_ratio: 0.5

signal:
  hold_duration_ms: 1000
  sustain_threshold: 0.1
  slope_filter:
    enabled: false
    period: 10
    threshold: 0.01
  cvd_window_minutes: 5
  obi_weight: 0.4
  ofi_weight: 0.3
  cvd_weight: 0.2
  micro_price_weight: 0.1
  composite_threshold: 0.55

risk:
  max_drawdown_percent: 10.0
  max_position_ratio: 0.5

adaptive_position_sizing:
  enabled: false
  num_trades: 10
  reduction_step: 0.1
  min_ratio: 0.5
